name: mrx
favicon: null
layout_spectrum: 1
typography_spectrum: 0
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: X-Bay development updates
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262626'
    - '#4e4e4e'
    - '#877d62'
    - '#89b79a'
    - '#fefefe'
  brandStrength: 0.5625
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
